package operacions;

public class Calculando extends javax.swing.JFrame {
    char operacion = '0';
    int op1;
    int op2;
    boolean result = false;
    /**
     * Creates new form Calculando
     */
    public Calculando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operaciones = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();
        botonera = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bpor = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bentre = new javax.swing.JButton();
        bmas = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bmenos = new javax.swing.JButton();
        bigual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A miña calculadora");

        pantalla.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setText("0");

        javax.swing.GroupLayout operacionesLayout = new javax.swing.GroupLayout(operaciones);
        operaciones.setLayout(operacionesLayout);
        operacionesLayout.setHorizontalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla)
                .addContainerGap())
        );
        operacionesLayout.setVerticalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonera.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        b1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        botonera.add(b1);

        b2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        botonera.add(b2);

        b3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        botonera.add(b3);

        bC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bC.setText("C");
        bC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCActionPerformed(evt);
            }
        });
        botonera.add(bC);

        b4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        botonera.add(b4);

        b5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        botonera.add(b5);

        b6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        botonera.add(b6);

        bpor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bpor.setText("x");
        bpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bporActionPerformed(evt);
            }
        });
        botonera.add(bpor);

        b7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        botonera.add(b7);

        b8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        botonera.add(b8);

        b9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        botonera.add(b9);

        bentre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bentre.setText("/");
        bentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentreActionPerformed(evt);
            }
        });
        botonera.add(bentre);

        bmas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bmas.setText("+");
        bmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmasActionPerformed(evt);
            }
        });
        botonera.add(bmas);

        b0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        botonera.add(b0);

        bmenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bmenos.setText("-");
        bmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmenosActionPerformed(evt);
            }
        });
        botonera.add(bmenos);

        bigual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bigual.setText("=");
        bigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigualActionPerformed(evt);
            }
        });
        botonera.add(bigual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonera, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(operaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("1");
        }else{
            pantalla.setText(pantalla.getText() + "1");
        }
        result = false;
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("2");
        }else{
            pantalla.setText(pantalla.getText() + "2");
        }
        result = false;
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("3");
        }else{
            pantalla.setText(pantalla.getText() + "3");
        }
        result = false;
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("4");
        }else{
            pantalla.setText(pantalla.getText() + "4");
        }
        result = false;
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("5");
        }else{
            pantalla.setText(pantalla.getText() + "5");
        }
        result = false;
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("6");
        }else{
            pantalla.setText(pantalla.getText() + "6");
        }
        result = false; 
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("7");
        }else{
            pantalla.setText(pantalla.getText() + "7");
        }
        result = false; 
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("8");
        }else{
            pantalla.setText(pantalla.getText() + "8");
        }
        result = false;
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       if(pantalla.getText().equals("0") || result){
            pantalla.setText("9");
        }else{
            pantalla.setText(pantalla.getText() + "9");
        }
       result = false;
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        if(pantalla.getText().equals("0") || result){
            pantalla.setText("0");
        }else{
            pantalla.setText(pantalla.getText() + "0");
        }
        result = false;
    }//GEN-LAST:event_b0ActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        operacion = '0';
        op1 = 0;
        op2 = 0;
        pantalla.setText("0");
        result = false;
    }//GEN-LAST:event_bCActionPerformed

    private void bporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bporActionPerformed
        op1 = Integer.parseInt(pantalla.getText());
        operacion = '*';
        pantalla.setText("");
        result = false;
    }//GEN-LAST:event_bporActionPerformed

    private void bentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentreActionPerformed
        op1 = Integer.parseInt(pantalla.getText());
        operacion = '/';
        pantalla.setText("");
        result = false;
    }//GEN-LAST:event_bentreActionPerformed

    private void bmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmasActionPerformed
        op1 = Integer.parseInt(pantalla.getText());
        operacion = '+';
        pantalla.setText("");
        result = false;
    }//GEN-LAST:event_bmasActionPerformed

    private void bmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmenosActionPerformed
        op1 = Integer.parseInt(pantalla.getText());
        operacion = '-';
        pantalla.setText("");
        result = false;
    }//GEN-LAST:event_bmenosActionPerformed

    private void bigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigualActionPerformed
        if(operacion == '0'){
            pantalla.setText(pantalla.getText());
        }else if(operacion == '+' || operacion == '-' || operacion == '*' || operacion == '/'){
            op2 = Integer.parseInt(pantalla.getText());
        }
        pantalla.setText(Integer.toString(calcular(op1, op2, operacion)));
        operacion = '0';
        op1 = 0;
        op2 = 0;
        result = true;
    }//GEN-LAST:event_bigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculando().setVisible(true);
            }
        });
    }
   
        int calcular(int op1, int op2, char operacion){
        switch(operacion){
            case '+':   return op1 + op2;
            case '-':   return op1 - op2;
            case '*':   return op1 * op2;
            case '/':   return op1 / op2;
            default:    return 0;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bC;
    private javax.swing.JButton bentre;
    private javax.swing.JButton bigual;
    private javax.swing.JButton bmas;
    private javax.swing.JButton bmenos;
    private javax.swing.JPanel botonera;
    private javax.swing.JButton bpor;
    private javax.swing.JPanel operaciones;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
