/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operacions;

/**
 *
 * @author mbdorca
 */
public class Calculando extends javax.swing.JFrame {

    /**
     * Creates new form Calculando
     */
    public Calculando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operaciones = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();
        botonera = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        bpor = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bentre = new javax.swing.JButton();
        bmas = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bmenos = new javax.swing.JButton();
        bigual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A miña calculadora");

        pantalla.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla.setText("0");

        javax.swing.GroupLayout operacionesLayout = new javax.swing.GroupLayout(operaciones);
        operaciones.setLayout(operacionesLayout);
        operacionesLayout.setHorizontalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla)
                .addContainerGap())
        );
        operacionesLayout.setVerticalGroup(
            operacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        botonera.setLayout(new java.awt.GridLayout(4, 4, 5, 5));

        b1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b1.setText("1");
        botonera.add(b1);

        b2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b2.setText("2");
        botonera.add(b2);

        b3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b3.setText("3");
        botonera.add(b3);

        bC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bC.setText("C");
        botonera.add(bC);

        b4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b4.setText("4");
        botonera.add(b4);

        b5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b5.setText("5");
        botonera.add(b5);

        b6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b6.setText("6");
        botonera.add(b6);

        bpor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bpor.setText("x");
        botonera.add(bpor);

        b7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b7.setText("7");
        botonera.add(b7);

        b8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b8.setText("8");
        botonera.add(b8);

        b9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b9.setText("9");
        botonera.add(b9);

        bentre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bentre.setText("/");
        botonera.add(bentre);

        bmas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bmas.setText("+");
        botonera.add(bmas);

        b0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        b0.setText("0");
        botonera.add(b0);

        bmenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bmenos.setText("-");
        botonera.add(bmenos);

        bigual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bigual.setText("=");
        botonera.add(bigual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonera, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(operaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bC;
    private javax.swing.JButton bentre;
    private javax.swing.JButton bigual;
    private javax.swing.JButton bmas;
    private javax.swing.JButton bmenos;
    private javax.swing.JPanel botonera;
    private javax.swing.JButton bpor;
    private javax.swing.JPanel operaciones;
    private javax.swing.JTextField pantalla;
    // End of variables declaration//GEN-END:variables
}
